; instagramSOBS
[settings]
headless = false
safety_checks = true
output =
playwright_default = true
scroll_duration = 120

[profile]
username = christocane_

[misc]
div = div._ac78
ignore_suggested_for_you = true ; not used
